eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:2333/school?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
management:
  security:
    enable:false
